### ISSUE TITLE
MySQL Console Spam Error

### ISSUE THREAD

**Issue by NicoNekoDev** [Xibalba/ZHorse#45]
I updated the plugin and this is what I got.
https://pastebin.com/v4xqU031

Edit: this happen when a player join.

Edit 2: There's more: https://pastebin.com/u4ZKEy5R

**Comment by Zedd7** [comment]
It says that "Table 'pikacraf_server.zh__pending_message' doesn't exist". Notice that there are two "_" characters in the prefix name, make sure that this is wanted.

**Comment by NicoNekoDev** [comment]
I checked the mysql, i use the same config for mysql. But the table is not there. Anyway i delete the zhorse tabel and generate new one. The second error showed up. Sorry for my english. :)

**Comment by NicoNekoDev** [comment]
And the double _ is okay, for others tabela works fine.

**Comment by Zedd7** [comment]
It looks like your MySQL server is outdated, because an exception is thrown when ZHorse tries to create a table using a specified precision for the DATETIME type.

You should [upgrade your MySQL server to the version 5.7](https://dev.mysql.com/doc/refman/5.7/en/upgrading.html) or switch to a SQLite database and import your data with the '/zh admin import' command.
