### ISSUE TITLE
/zh sell doesn't allow players to mount to do /zh buy

### ISSUE THREAD

**Issue by P3NGU1N101** [Xibalba/ZHorse#49]
Hey, can you change it so that /zh sell allows players to mount the horse to do /zh buy or something like you right click the horse you want to purchase after you do /zh buy. Something like that.
When you have a horse protected it doesn't allow you to mount the horse you are selling which means they can't do /zh buy. It would just be more convenient

Another cool RPG idea would be allowing horse genders

**Comment by Zedd7** [comment]
Hello,

Sorry but allowing players to mount horses for sale is not planned.
This is because I can't prevent players (in a simple way) from stealing locked horses instead of testing them. And this is why the horse stats are displayed when a player right-click a horse for sale.

However, horse sellers have 3 options remaining : 
1. Simply unlock their horses for sale (put them in restricted mode) so that potential buyers can try them and decide to buy them or not. Of course, buyers would have to return the horses to their stable.
2. Do what is suggested in 1. but provide a testing ground to prevent players from running away with the horses.
3. Keep the horses locked. Buyers can see the stats by right-clicking the horses and buy them using either `/zh buy -t playerName -i horseID` or `/zh buy -t playerName horseName` or `/zh buy playerName -i horseID`.

can unlock their horses for sale (put them in restricted mode) and provide a testing ground so that potential buyers
