### ISSUE TITLE
/zh List extra tag to identify species

### ISSUE THREAD

**Issue by ViceDellos** [Xibalba/ZHorse#61]
## Feature request

- [x] Add a tag to the horse listings identifying it as a horse/donkey/mule/llama/zombie horse/skeleton horse.
- [x] Add a command flag `-v <variant>` to display only horse of the said variant with `/zh list`
- [x] Display the horse variant in /zh info
- [x] Allow use of the flag with `/zh spawn`
- [x] Apply a variant filter to `/zh admin burial` and `/zh admin clear`

Currently /zh list will give you

```
-+- Your horses (1/20) -+-
1 - Shadowfax [locked] [protected] (favorite)
```

here's an example of what I mean including the tag

```
-+- Your horses (2/20) -+-
1 - H|Shadowfax [locked] [protected] (favorite)
2 - D|Ior [Locked] [protected]
```

Other options:
```
-+- Your horses (5/20) -+-
1 - <H> Shadowfax [locked] [protected] (favorite)
2 - [D] Ior [Locked] [protected]
3 - {S} Skeletor [locked] [protected]
4 - Poocha [locked] [protected] {llama}
5 - Zedd [locked] [protected] [Z]
```

**Comment by Zedd7** [comment]
Current preferred display :
`1 - Shadowfax <H> [locked] [protected] (favorite)`

That's because :
- horse name should be found fast when browsing the horse list.
- [locked], [restricted], [shared], [protected] and (favorite) are optional flags and should then come after the horse variant.
- `<H>` is different from [protection mode] and (favorite) and is kind of a wink to Java's generic argument types `<T>`

**Comment by ViceDellos** [comment]
that makes sense.

can you have "/zh list h" filter so it only displays horses without having to redo how the entire list is generated?

**Comment by Zedd7** [comment]
The simplest (code-wise) way to do this would be to add a `-v <variant>` flag.
Adding a non-flagged parameter would either be impossible or prevent player from parsing horse names instead of using `-i <horse ID>`.

If you are ok with the first option, it should be doable for 1.6.8.

**Comment by ViceDellos** [comment]
yeah doing it like that sounds good
