### ISSUE TITLE
It says that 

### ISSUE THREAD

**Issue by GoldenGhost** [Xibalba/ZHorse#63]
It says that its disabled in my world, I'm on a server that is on 1.11.2

**Comment by Zedd7** [comment]
Please follow [the provided pattern](https://github.com/Xibalba/ZHorse/blob/master/ISSUE_TEMPLATE.md) for issues or I won't be able to help you.

**Comment by Midnight9746** [comment]
Just saw this thread and at the bottom of the config you'll see:

world:
    enabled: true
    crossable: flase
  world_nether:
    enabled:  flase
    crossable:  flase
  world_the_end:
    enabled:  flase
    crossable:  flase

Turn 'enable: false' to 'enable: true' if you're wishing to allow ZH on that world, and then do the same for crossable if you're wishing to allow /zh here to move horses across worlds. (Say the horse is in the overworld and you're in the nether, this will allow you to do /zh here in the nether to call the overworld horse.)

If you have different overworlds, I think changing 'world:' to the name you have like 'myserver:' should make it work for that world too. But since I didn't code the plugin, I'm not sure if it fetches a custom world input like that.

**Comment by Zedd7** [comment]
Here `world:` is a keyword for world/map/anything of that kind so changing it to `server:` or anything else won't work.

Also be careful to spell `false` correctly (not flase).

**Comment by Midnight9746** [comment]
@Zedd7 didn't realized I did that.... whoops
