### ISSUE TITLE
Don't display empty messages

### ISSUE THREAD

**Issue by Remski01** [Xibalba/ZHorse#67]
1, 

When i player entered only the command and not a urgement he get a bunch of links, Wiki, Legend, And Usage. Can those be removed? I tryed to just leave it blank(Just as " ") but that result in an empty line.

2, 

For some reason the plugin decide to drop a error in console.

error: https://pastebin.com/SSVK8hTq
Config: https://pastebin.com/e10ap5Ap

**Comment by Zedd7** [comment]
1. This is currently not possible, as messages are sent even if they are empty (it used to be useful for custom new lines but I can remove that in the next update). By the way, why does it bother you ? Those messages only appear when the command is incomplete or incorrect.
2. You should do `/zh settings language EN -p <the_player_name> -a` in order to fix that (or whatever language you want). I guess that at some point your created a language "Custom" and reloaded the config, which gave him access to the command `/zh settings language Custom`. This is not a big deal as this player is currently experiencing ZHorse in English, as it is the default language and it replaces missing or incomplete custom languages.

**Comment by Remski01** [comment]
1, Because we are a Dutch server and player cannot read english. And its confussing for a player. We have some ingame command pages and dont use links to websites or anything like that.

2, Thank you.

**Comment by Zedd7** [comment]
I understand. But then you should set NL as the default language so that every new player has it as ZHorse's language and doesn't need to do /zh settings language NL.
As this feature requests only minor changes to the code and is the only issue at the moment, I will provide you an alternate release of 1.6.8 containing the feature.

**Comment by Remski01** [comment]
And i have a bit of a question. You're plugin supports also Llames and Donkey's But we can only use one of these of we dont wanna do "Horse, Donkey of Llama" is there a way to add a code that the plugin checks on what he sits and send that to the player.

Short version:
That the plugin checks on what he sits and put that in "as example: [ZHorse] You need to tame this donkey first!" (code version: > <green>[ZHorse] <yellow> You need to tame this <animal> first!)

**Comment by Zedd7** [comment]
Sorry but even if I like precise messages, this would require a lot of changes for not much, so I won't do it. You can however change the message to use a more generic word instead of "horse" ;)

**Comment by Remski01** [comment]
Oki,

But i have a other question about the /zh rename command. Is it based on what for animal you sitted last? And also, I used it but the name of that horse did not change.

Can you maybe add that players can use /zh rename [Old-name] [New-Name]?

**Comment by Zedd7** [comment]
It is only based on the config list of random names, if it is enabled. If the horse name didn't change, there may be an error log in the console. If so, create a new issue
